# Generated by Django 4.0.3 on 2022-04-26 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='board',
            old_name='writr',
            new_name='writer',
        ),
    ]
